# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoAmTKnnR3qRlJPt2UQaFqM6bbvUOWqE
"""

import streamlit as st

# Configurar la página
st.set_page_config(page_title="Mi Aplicación", page_icon=":guardsman:", layout="wide")

# Cargar la imagen como fondo
st.markdown(
    """
    <style>
    .stApp {
        background-image: url("data:image/jpeg;base64,{}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }
    </style>
    """.format(st.image("valorant.jpg", use_column_width=True, caption=None, output_format="JPEG")),
    unsafe_allow_html=True
)

# Contenido de la aplicación
st.title("Bienvenido a mi aplicación")
st.write("Esta es una aplicación de ejemplo con una imagen de fondo.")